version: '3.8'

services:
    spring-boot-app:
        image: openjdk:18
        container_name: spring-boot-app
        working_dir: /app
        volumes:
            - ./target/cloud-0.0.1-SNAPSHOT.jar:/app/cloud-0.0.1-SNAPSHOT.jar
        ports:
            - "8084:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crypto
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
        depends_on:
            - db
        command: ["java", "-jar", "/app/cloud-0.0.1-SNAPSHOT.jar"]

    db:
        image: postgres:16
        container_name: postgres-db
        restart: always
        ports:
            - "5434:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: crypto
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
