<!DOCTYPE html>
<html lang="en" data-theme="mytheme">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inscription Réussie 🎉</title>
        <link rel="stylesheet" href="/css/tailwind-output.css">
        <%--    <link rel="stylesheet" href="/flyonui/dist/full.css">--%>
    </head>
    <body class="bg-white flex items-start justify-center pt-2">
        <div class="flex flex-col items-center ">
            <h1 class="text-3xl font-bold text-green-600 mb-4">🎉 Félicitations !</h1>
            <p class="text-gray-700 text-center mb-4 text-lg">
                ✅ Votre inscription a été réussie.<br>
                📩 Une dernière étape est nécessaire : <br>
                <span class="font-semibold">Vérifiez votre e-mail pour activer votre compte.</span>
            </p>
            <a href="/auth/login" class="btn btn-success btn-sm w-20 text-white">
                Se connecter
            </a>
        </div>
    </body>
    <script src="/flyonui/flyonui.js"></script>
</html>